repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.7.6
    hooks:
      # Update the uv lockfile
      - id: uv-lock
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    - id: check-added-large-files
      name: "Check for added large files"
    - id: check-toml
      name: "Check TOML"
    - id: check-yaml
      name:  Check YAML"
      args:
      - --unsafe
    # - id: end-of-file-fixer
    #   name: "Fix end of files"
    # - id: trailing-whitespace
    #   name: "Trim trailing whitespaces"
  - repo: local
    hooks:
      - id: gen-yaml-docs
        name: Run script to generate YAML docs
        entry: bash -c "cd doc/yaml && uv run make_yaml_README.py"
        language: system
        pass_filenames: false
        verbose: true
        files: src/kgsteward/yamlconfig.py
