import json
import jsonschema_markdown
from kgsteward.grlc import GrlcDecorators

# Reference doc for the grlc decorators is autogenerated from the pydantic
# model, mirroring doc/yaml/make_yaml_README.py -- but kept separate from the
# kgsteward YAML configuration doc.

schema = GrlcDecorators.model_json_schema()
schema["description"] = "grlc decorators recognised in the `#+` comment block of a SPARQL query file"

with open( "grlc.schema.json", "w" ) as f:
    f.write( json.dumps( schema, indent = 2 ))

with open( "grlc.schema.md", "w" ) as f:
    f.write( """<sup>back to [TOC](../README.md)</sup>

# grlc decorator syntax

`kgsteward` optionally understands [grlc](https://grlc.io) decorators in SPARQL
query files.

* A decorator is a line starting with `#+` (at the beginning of the line), for
example `#+ summary: Count all triples`. Because it is a SPARQL comment, the
file stays a valid SPARQL query.

* Every `#+` line in the file is collected and the remainder is parsed as a
single YAML document. A file without any `#+` line is handled exactly as
before (its query is used unchanged and only minimally documented).

* Query parameters written in grlc style (`?_name`, `?__name`, with optional
type suffixes `_iri`, `_number`, `_integer`, `_literal`, `_<prefix>_<datatype>`
or a language tag such as `_en`) receive their `defaults` value by
substitution. Parameters without a default are left as ordinary SPARQL
variables.

The recognised decorators are described below.

""" )
    txt = jsonschema_markdown.generate( schema, hide_empty_columns = True )
    big_space = "&nbsp;" * 40
    txt = txt.replace( "| Description |", "|" + big_space + "Description" + big_space + "|" )  # match YAML doc table layout
    f.write( txt + "\n\n<sup>back to [TOC](../README.md)</sup>" )
