"""grlc decorator support for kgsteward SPARQL query files.

A query file may carry `grlc <https://grlc.io>`_ decorators as a block of
`#+` YAML comment lines, e.g.::

    #+ summary: All triples of a blue car
    #+ tags:
    #+   - example
    SELECT * WHERE { ?s ?p ?o }

This module

  * parses the `#+` block into a validated :class:`GrlcDecorators` object,
  * substitutes grlc parameter ``defaults`` into the query text, and
  * emits RDF documenting the query in the SIB *sparql-examples* vocabulary.

It is deliberately kept independent from :mod:`kgsteward.yamlconfig` (the
kgsteward configuration) so that grlc support can evolve on its own.  As with
the kgsteward YAML documentation, the decorator reference is autogenerated from
the pydantic model below (see ``doc/grlc/make_grlc_README.py``); descriptions
therefore live on the model, not in hand-written docs.
"""

import re
import yaml
from typing import Optional, List, Any, Literal

from pydantic import BaseModel, Field, ConfigDict

from rdflib import Graph, URIRef, Literal as RdfLiteral, Namespace
from rdflib.namespace import RDF, RDFS

# --------------------------------------------------------------------------- #
# Decorator descriptions.  Kept in a local dict (mirroring the yamlconfig
# mechanism, but separate from it) so the reference doc can be autogenerated.
# --------------------------------------------------------------------------- #

description = {
    "summary"         : "Short one-line summary of the query, shown next to its name.",
    "description"     : "Longer human-readable description of what the query does.",
    "endpoint"        : "SPARQL endpoint the query is meant to run against. Takes precedence over any endpoint supplied by kgsteward when documenting the query (schema:target).",
    "endpoint_in_url" : "Whether the endpoint may be overridden through a URL parameter. grlc HTTP-API option, kept for compatibility but not reflected in the RDF documentation.",
    "endpoint_method" : "HTTP method used to send the query to the endpoint (GET or POST). grlc HTTP-API option, not reflected in the RDF documentation.",
    "method"          : "HTTP method exposed by the generated API operation (GET or POST). grlc HTTP-API option, not reflected in the RDF documentation.",
    "pagination"      : "Page size for paginated results. grlc HTTP-API option, not reflected in the RDF documentation.",
    "tags"            : "List of tags used to group related queries. Emitted as schema:keywords.",
    "defaults"        : "List of single-key mappings giving default values for query parameters (?_name). Applied by substitution into the returned query; parameters without a default are left untouched.",
    "enumerate"       : "List of parameters offered as an enumerated choice. grlc HTTP-API option, not reflected in the RDF documentation.",
    "transform"       : "SPARQLTransformer structure used to reshape results. grlc option, not reflected in the RDF documentation.",
}

def describe( term ):
    return description[ term ].strip()

# --------------------------------------------------------------------------- #
# The grlc decorator model
# --------------------------------------------------------------------------- #

class GrlcDecorators( BaseModel ):
    """Validated grlc decorator block (the leading `#+` YAML comments).

    Unknown keys are preserved (``extra='allow'``) so that grlc decorators not
    modelled here -- or added by kgsteward later -- pass through untouched
    rather than raising, matching grlc's own lenient behaviour.
    """
    model_config = ConfigDict( extra = "allow", populate_by_name = True )

    summary         : Optional[ str ]                     = Field( None, title = "Summary",          description = describe( "summary" ))
    description      : Optional[ str ]                     = Field( None, title = "Description",      description = describe( "description" ))
    endpoint         : Optional[ str ]                     = Field( None, title = "Endpoint",         description = describe( "endpoint" ))
    endpoint_in_url  : Optional[ bool ]                    = Field( None, title = "Endpoint in URL",  description = describe( "endpoint_in_url" ))
    endpoint_method  : Optional[ Literal[ "GET", "POST" ]] = Field( None, alias = "endpoint-method",  title = "Endpoint method", description = describe( "endpoint_method" ))
    method           : Optional[ Literal[ "GET", "POST" ]] = Field( None, title = "Method",           description = describe( "method" ))
    pagination       : Optional[ int ]                     = Field( None, title = "Pagination",       description = describe( "pagination" ))
    tags             : Optional[ List[ str ]]              = Field( None, title = "Tags",             description = describe( "tags" ))
    defaults         : Optional[ List[ dict ]]             = Field( None, title = "Defaults",         description = describe( "defaults" ))
    enumerate_       : Optional[ List[ Any ]]              = Field( None, alias = "enumerate",         title = "Enumerate", description = describe( "enumerate" ))
    transform        : Optional[ dict ]                    = Field( None, title = "Transform",        description = describe( "transform" ))

# --------------------------------------------------------------------------- #
# Decorator block extraction & parsing
# --------------------------------------------------------------------------- #

def extract_decorator_block( text ):
    """Return the YAML string collected from the `#+` lines, or None if the
    file carries no `#+` line.  Follows grlc: every line starting with `#+`
    (at column 0) is collected, wherever it sits in the file."""
    lines = [ line[ 2: ] for line in text.splitlines() if line.startswith( "#+" ) ]
    return "\n".join( lines ) if lines else None

def parse_decorators( text ):
    """Parse the grlc `#+` decorator block into a :class:`GrlcDecorators`.

    Returns ``None`` when the file has no `#+` line.  Malformed YAML in the
    block is treated leniently (as an empty decorator set), matching grlc;
    type errors on recognised keys still raise via pydantic."""
    block = extract_decorator_block( text )
    if block is None:
        return None
    try:
        data = yaml.safe_load( block )
    except yaml.YAMLError:
        data = None
    if not isinstance( data, dict ):
        data = {}
    return GrlcDecorators( **data )

# --------------------------------------------------------------------------- #
# Query-form detection (SELECT / ASK / CONSTRUCT / DESCRIBE / UPDATE)
# --------------------------------------------------------------------------- #

def strip_comments( q ):
    """Remove SPARQL line comments, respecting <IRIs> and string literals so a
    `#` inside them is never mistaken for a comment."""
    out, i, n = [], 0, len( q )
    while i < n:
        c = q[ i ]
        if c in "\"'":                                  # string literal (short or long form)
            quote  = c
            triple = q[ i:i + 3 ] == quote * 3
            end    = quote * 3 if triple else quote
            out.append( q[ i:i + len( end ) ] ); i += len( end )
            while i < n:
                if q[ i ] == "\\" and not triple:       # escape inside a short string
                    out.append( q[ i:i + 2 ] ); i += 2; continue
                if q[ i:i + len( end ) ] == end:
                    out.append( end ); i += len( end ); break
                out.append( q[ i ] ); i += 1
            continue
        if c == "<":                                    # IRIREF: '#' is legal, not a comment
            j = q.find( ">", i )
            if j == -1:
                out.append( q[ i: ] ); break
            out.append( q[ i:j + 1 ] ); i = j + 1; continue
        if c == "#":                                    # comment: drop to end of line
            j = q.find( "\n", i )
            if j == -1:
                break
            i = j; continue
        out.append( c ); i += 1
    return "".join( out )

_FORM = re.compile(
    r"\b(SELECT|ASK|CONSTRUCT|DESCRIBE|INSERT|DELETE|LOAD|CLEAR|DROP|CREATE|COPY|MOVE|ADD)\b",
    re.IGNORECASE,
)
_UPDATE_KEYWORDS = { "INSERT", "DELETE", "LOAD", "CLEAR", "DROP", "CREATE", "COPY", "MOVE", "ADD" }

def detect_form( text ):
    """Return the query form: 'SELECT', 'ASK', 'CONSTRUCT', 'DESCRIBE',
    'UPDATE', or None if no form keyword is found."""
    s = strip_comments( text )
    s = re.sub( r"(?im)^\s*PREFIX\s+\S*\s*<[^>]*>\s*$", "", s )   # drop PREFIX / BASE so a
    s = re.sub( r"(?im)^\s*BASE\s+<[^>]*>\s*$", "", s )           # keyword inside an IRI can't match
    m = _FORM.search( s )
    if not m:
        return None
    kw = m.group( 1 ).upper()
    return "UPDATE" if kw in _UPDATE_KEYWORDS else kw

# --------------------------------------------------------------------------- #
# grlc parameter defaults substitution
# --------------------------------------------------------------------------- #

# ?_name (required) / ?__name (optional), optional type suffix:
#   _iri | _number | _integer | _literal | _<prefix>_<datatype> | _<lang>
_PARAM = re.compile(
    r"\?(?P<req>_{1,2})(?P<name>[A-Za-z0-9]+)"
    r"(?:_(?P<type>iri|number|integer|literal))?"
    r"(?:_(?P<pfx>[A-Za-z0-9]+)_(?P<dt>[A-Za-z0-9]+))?"
    r"(?:_(?P<lang>[A-Za-z]+))?"
)

def _render_value( m, value ):
    """Render *value* into SPARQL text according to the parameter's type suffix."""
    t    = m.group( "type" )
    lang = m.group( "lang" )
    pfx  = m.group( "pfx" )
    dt   = m.group( "dt" )
    s    = str( value )
    if t == "iri":
        return "<" + s + ">"
    if t in ( "number", "integer" ):
        return s
    if lang:
        return '"' + s + '"@' + lang
    if pfx and dt:
        return '"' + s + '"^^' + pfx + ":" + dt
    return '"' + s + '"'                                  # literal / untyped

def apply_defaults( text, decorators ):
    """Substitute grlc parameter `defaults` into *text*.  Parameters without a
    default are left as valid SPARQL variables, so the query still runs."""
    if decorators is None or not decorators.defaults:
        return text
    defaults = {}
    for entry in decorators.defaults:
        if isinstance( entry, dict ):
            defaults.update( entry )
    if not defaults:
        return text
    def repl( m ):
        name = m.group( "name" )
        return _render_value( m, defaults[ name ] ) if name in defaults else m.group( 0 )
    return _PARAM.sub( repl, text )

# --------------------------------------------------------------------------- #
# RDF documentation (SIB sparql-examples vocabulary)
# --------------------------------------------------------------------------- #

SH     = Namespace( "http://www.w3.org/ns/shacl#" )
SCHEMA = Namespace( "https://schema.org/" )
SPEX   = Namespace( "https://purl.expasy.org/sparql-examples/ontology#" )

_FORM_TO_SH = {
    "SELECT"    : ( SH.SPARQLSelectExecutable,    SH.select    ),
    "ASK"       : ( SH.SPARQLAskExecutable,       SH.ask       ),
    "CONSTRUCT" : ( SH.SPARQLConstructExecutable, SH.construct ),
    "DESCRIBE"  : ( SH.SPARQLDescribeExecutable,  SH.describe  ),
    "UPDATE"    : ( SH.SPARQLUpdateExecutable,    SH.update    ),
}

def build_graph( text, name, decorators, endpoint = None, form = None ):
    """Build an rdflib.Graph documenting the query (query text as authored)."""
    g = Graph()
    g.bind( "sh",     SH )
    g.bind( "schema", SCHEMA )
    g.bind( "spex",   SPEX )
    g.bind( "rdfs",   RDFS )

    base = ( endpoint.rstrip( "/" ) + "/.well-known/sparql-examples/"
             if endpoint else "https://purl.expasy.org/kgsteward/query/" )
    subj = URIRef( base + name )

    g.add(( subj, RDF.type, SH.SPARQLExecutable ))
    if form in _FORM_TO_SH:
        cls, pred = _FORM_TO_SH[ form ]
        g.add(( subj, RDF.type, cls ))
        g.add(( subj, pred, RdfLiteral( text )))          # query as authored

    comment = ( decorators.description or decorators.summary ) if decorators else None
    if comment:
        g.add(( subj, RDFS.comment, RdfLiteral( comment )))

    target = ( decorators.endpoint if decorators else None ) or endpoint   # #+ endpoint wins
    if target:
        g.add(( subj, SCHEMA.target, URIRef( target )))

    if decorators and decorators.tags:
        for tag in decorators.tags:
            g.add(( subj, SCHEMA.keywords, RdfLiteral( tag )))

    return g

# --------------------------------------------------------------------------- #
# Public entry point
# --------------------------------------------------------------------------- #

def parse_query( text, name, endpoint = None ):
    """Parse a SPARQL query file that may carry grlc `#+` decorators.

    Returns ``(query, graph)`` where

      * ``query`` is the query text with grlc parameter `defaults` substituted
        in.  The `#+` block is left in place and prefixes are not injected;
        files without decorators come back unchanged.
      * ``graph`` is an :class:`rdflib.Graph` documenting the query in the SIB
        sparql-examples vocabulary.

    ``name`` is the query identifier (kgsteward derives it from the file name).
    ``endpoint``, when given, sets the sparql-examples base IRI and the default
    ``schema:target``.
    """
    decorators = parse_decorators( text )
    form       = detect_form( text )
    query      = apply_defaults( text, decorators )
    graph      = build_graph( text, name, decorators, endpoint = endpoint, form = form )
    return query, graph
