"""grlc decorator support for kgsteward SPARQL query files.

A query file may carry `grlc <https://grlc.io>`_ decorators as a block of
`#+` YAML comment lines. This module

  * parses the `#+` block into a validated :class:`GrlcDecorators` object,
  * substitutes grlc parameter ``defaults`` into the query text,
  * emits RDF documenting the query in the SIB *sparql-examples* vocabulary, and
  * emits, from the query-form extension (``selector`` / ``form`` decorators),
    RDF describing dynamic input forms in the kgsteward vocabulary
    (see ``doc/grlc/queryform-extension.md``).

Queries are accumulated into a :class:`GrlcCatalog`, whose internal graph is a
single backing store for both the sparql-editor (via :meth:`serialize`) and an
MCP server (via :meth:`list`, :meth:`get`, :meth:`search`, or SPARQL over the
graph).

The module is deliberately independent from :mod:`kgsteward.yamlconfig`.  As
with the kgsteward YAML documentation, the decorator reference is autogenerated
from the pydantic models (see ``doc/grlc/make_grlc_README.py``); descriptions
live on the models.
"""

import re
import yaml
from typing import Optional, List, Union, Literal, Annotated

from pydantic import BaseModel, Field, ConfigDict, field_validator

from rdflib import Graph, URIRef, BNode, Literal as RdfLiteral, Namespace
from rdflib.namespace import RDF, RDFS, XSD
from rdflib.collection import Collection

# --------------------------------------------------------------------------- #
# Decorator descriptions (local dict, mirroring yamlconfig but separate).
# --------------------------------------------------------------------------- #

description = {
    # standard grlc
    "summary"         : "Short one-line summary of the query, shown next to its name. Mandatory when a query uses grlc notation. Emitted as rdfs:label.",
    "description"     : "Longer human-readable description of what the query does. Emitted as rdfs:comment (falls back to summary when absent).",
    "endpoint"        : "SPARQL endpoint the query is meant to run against. Takes precedence over any endpoint supplied by kgsteward when documenting the query (schema:target).",
    "endpoint_in_url" : "Whether the endpoint may be overridden through a URL parameter. grlc HTTP-API option, not reflected in the RDF documentation.",
    "endpoint_method" : "HTTP method used to send the query to the endpoint (GET or POST). grlc HTTP-API option, not reflected in the RDF documentation.",
    "method"          : "HTTP method exposed by the generated API operation (GET or POST). grlc HTTP-API option, not reflected in the RDF documentation.",
    "pagination"      : "Page size for paginated results. grlc HTTP-API option, not reflected in the RDF documentation.",
    "tags"            : "List of tags used to group related queries. Emitted as schema:keywords.",
    "defaults"        : "List of single-key mappings giving default values for grlc parameters (?_name). Applied by substitution into the returned query; parameters without a default are left untouched.",
    "enumerate"       : "List of parameters offered as an enumerated choice. grlc HTTP-API option, not reflected in the RDF documentation.",
    "transform"       : "SPARQLTransformer structure used to reshape results. grlc option, not reflected in the RDF documentation.",
    # kgsteward extensions
    "source"          : "Provenance of the query (e.g. an upstream sparql-examples file). Emitted as dct:source.",
    "citation"        : "Bibliographic citation to credit when using the query. Emitted as schema:citation.",
    "param"           : "Standalone parameter mechanism (list of single-key mappings). Recognised and preserved; substitution semantics are left to the parameter mechanism.",
    "selector"        : "Reusable input widgets that populate form fields. Declared on the query that provides the option values.",
    "form"            : "Declares this query as a dynamic input form: a list of string substitutions, each binding a target string to a selector widget.",
    # widget fields
    "w_id"            : "Widget identifier, minted as kgsteward:<id>.",
    "w_type"          : "Widget kind: select, checkbox, autocomplete (all query-backed), text (free text, optional regexp) or slider (numeric range).",
    "w_prompt"        : "Human-readable label shown for the widget (kgsteward:prompt).",
    "w_options"       : "Name of the query returning the option rows. Defaults to the query the selector is declared on (kgsteward:selectQuery).",
    "w_valueIndex"    : "1-based column of the option query's projection used as the value. A string is interpreted as a variable name (emitted as kgsteward:valueVar).",
    "w_nameIndex"     : "1-based column of the option query's projection used as the label. A string is interpreted as a variable name (emitted as kgsteward:nameVar).",
    "w_pattern"       : "Regular expression validating a free-text field (text widget only; kgsteward:pattern).",
    "w_min"           : "Lower bound of a slider (kgsteward:min).",
    "w_max"           : "Upper bound of a slider (kgsteward:max).",
    "w_step"          : "Step of a slider (kgsteward:step).",
    # form-field fields
    "f_target"        : "Verbatim string in the query body to be replaced (kgsteward:targetStr).",
    "f_widget"        : "Identifier of the selector widget providing the value (kgsteward:replaceWith).",
    "f_default"       : "Optional default value used when the field is left unset (kgsteward:default).",
}

def describe( term ):
    return description[ term ].strip()

# --------------------------------------------------------------------------- #
# Query-form extension models (query-form decorators)
# --------------------------------------------------------------------------- #

class _Widget( BaseModel ):
    model_config = ConfigDict( extra = "allow" )
    id     : str = Field( ..., title = "Widget id", description = describe( "w_id" ))
    prompt : str = Field( ..., title = "Prompt",    description = describe( "w_prompt" ))

class _QueryBackedWidget( _Widget ):
    options    : Optional[ str ]         = Field( None, title = "Options query", description = describe( "w_options" ))
    valueIndex : Union[ int, str ]       = Field( 1,    title = "Value index",   description = describe( "w_valueIndex" ))
    nameIndex  : Union[ int, str ]       = Field( 2,    title = "Name index",    description = describe( "w_nameIndex" ))

class SelectWidget( _QueryBackedWidget ):
    type : Literal[ "select" ] = Field( "select", title = "Widget type", description = describe( "w_type" ))

class CheckboxWidget( _QueryBackedWidget ):
    type : Literal[ "checkbox" ] = Field( "checkbox", title = "Widget type", description = describe( "w_type" ))

class AutocompleteWidget( _QueryBackedWidget ):
    type : Literal[ "autocomplete" ] = Field( "autocomplete", title = "Widget type", description = describe( "w_type" ))

class TextWidget( _Widget ):
    type    : Literal[ "text" ] = Field( "text", title = "Widget type", description = describe( "w_type" ))
    pattern : Optional[ str ]   = Field( None,   title = "Pattern",     description = describe( "w_pattern" ))

class SliderWidget( _Widget ):
    type : Literal[ "slider" ] = Field( "slider", title = "Widget type", description = describe( "w_type" ))
    min  : float = Field( ..., title = "Min",  description = describe( "w_min" ))
    max  : float = Field( ..., title = "Max",  description = describe( "w_max" ))
    step : float = Field( 1,   title = "Step", description = describe( "w_step" ))

Widget = Annotated[
    Union[ SelectWidget, CheckboxWidget, AutocompleteWidget, TextWidget, SliderWidget ],
    Field( discriminator = "type" ),
]

class FormFieldConf( BaseModel ):
    model_config = ConfigDict( extra = "allow" )
    target  : str           = Field( ..., title = "Target string", description = describe( "f_target" ))
    widget  : str           = Field( ..., title = "Widget id",     description = describe( "f_widget" ))
    default : Optional[ str ] = Field( None, title = "Default",    description = describe( "f_default" ))

# --------------------------------------------------------------------------- #
# The grlc decorator model
# --------------------------------------------------------------------------- #

class GrlcDecorators( BaseModel ):
    """Validated grlc decorator block (the `#+` YAML comments), plus the
    kgsteward query-form extension. Unknown keys are preserved (``extra='allow'``)."""
    model_config = ConfigDict( extra = "allow", populate_by_name = True )

    summary         : Optional[ str ]                     = Field( None, title = "Summary",          description = describe( "summary" ))
    description      : Optional[ str ]                     = Field( None, title = "Description",      description = describe( "description" ))
    endpoint         : Optional[ str ]                     = Field( None, title = "Endpoint",         description = describe( "endpoint" ))
    endpoint_in_url  : Optional[ bool ]                    = Field( None, title = "Endpoint in URL",  description = describe( "endpoint_in_url" ))
    endpoint_method  : Optional[ Literal[ "GET", "POST" ]] = Field( None, alias = "endpoint-method",  title = "Endpoint method", description = describe( "endpoint_method" ))
    method           : Optional[ Literal[ "GET", "POST" ]] = Field( None, title = "Method",           description = describe( "method" ))
    pagination       : Optional[ int ]                     = Field( None, title = "Pagination",       description = describe( "pagination" ))
    tags             : Optional[ List[ str ]]              = Field( None, title = "Tags",             description = describe( "tags" ))
    defaults         : Optional[ List[ dict ]]             = Field( None, title = "Defaults",         description = describe( "defaults" ))
    enumerate_       : Optional[ List[ dict ]]             = Field( None, alias = "enumerate",         title = "Enumerate", description = describe( "enumerate" ))
    transform        : Optional[ dict ]                    = Field( None, title = "Transform",        description = describe( "transform" ))
    # kgsteward extensions
    source           : Optional[ str ]                     = Field( None, title = "Source",           description = describe( "source" ))
    citation         : Optional[ str ]                     = Field( None, title = "Citation",         description = describe( "citation" ))
    param            : Optional[ List[ dict ]]             = Field( None, title = "Param",            description = describe( "param" ))
    selector         : Optional[ List[ Widget ]]           = Field( None, title = "Selector widgets", description = describe( "selector" ))
    form             : Optional[ List[ FormFieldConf ]]    = Field( None, title = "Input form",       description = describe( "form" ))

    @field_validator( "selector", mode = "before" )
    @classmethod
    def _default_widget_type( cls, v ):
        """A selector entry without an explicit `type` defaults to `select`."""
        if isinstance( v, list ):
            for item in v:
                if isinstance( item, dict ) and "type" not in item:
                    item[ "type" ] = "select"
        return v

# --------------------------------------------------------------------------- #
# Decorator block extraction & parsing
# --------------------------------------------------------------------------- #

def extract_decorator_block( text ):
    """Return the YAML string collected from the `#+` lines, or None."""
    lines = [ line[ 2: ] for line in text.splitlines() if line.startswith( "#+" ) ]
    return "\n".join( lines ) if lines else None

def parse_decorators( text ):
    """Parse the grlc `#+` decorator block into :class:`GrlcDecorators`.
    Returns ``None`` when the file has no `#+` line. Malformed YAML is treated
    leniently (empty decorator set); type errors on known keys raise."""
    block = extract_decorator_block( text )
    if block is None:
        return None
    try:
        data = yaml.safe_load( block )
    except yaml.YAMLError:
        data = None
    if not isinstance( data, dict ):
        data = {}
    return GrlcDecorators( **data )

# --------------------------------------------------------------------------- #
# Query-form detection
# --------------------------------------------------------------------------- #

def strip_comments( q ):
    """Remove SPARQL line comments, respecting <IRIs> and string literals."""
    out, i, n = [], 0, len( q )
    while i < n:
        c = q[ i ]
        if c in "\"'":
            quote  = c
            triple = q[ i:i + 3 ] == quote * 3
            end    = quote * 3 if triple else quote
            out.append( q[ i:i + len( end ) ] ); i += len( end )
            while i < n:
                if q[ i ] == "\\" and not triple:
                    out.append( q[ i:i + 2 ] ); i += 2; continue
                if q[ i:i + len( end ) ] == end:
                    out.append( end ); i += len( end ); break
                out.append( q[ i ] ); i += 1
            continue
        if c == "<":
            j = q.find( ">", i )
            if j == -1:
                out.append( q[ i: ] ); break
            out.append( q[ i:j + 1 ] ); i = j + 1; continue
        if c == "#":
            j = q.find( "\n", i )
            if j == -1:
                break
            i = j; continue
        out.append( c ); i += 1
    return "".join( out )

_FORM = re.compile(
    r"\b(SELECT|ASK|CONSTRUCT|DESCRIBE|INSERT|DELETE|LOAD|CLEAR|DROP|CREATE|COPY|MOVE|ADD)\b",
    re.IGNORECASE,
)
_UPDATE_KEYWORDS = { "INSERT", "DELETE", "LOAD", "CLEAR", "DROP", "CREATE", "COPY", "MOVE", "ADD" }

def detect_form( text ):
    """Return 'SELECT'|'ASK'|'CONSTRUCT'|'DESCRIBE'|'UPDATE' or None."""
    s = strip_comments( text )
    s = re.sub( r"(?im)^\s*PREFIX\s+\S*\s*<[^>]*>\s*$", "", s )
    s = re.sub( r"(?im)^\s*BASE\s+<[^>]*>\s*$", "", s )
    m = _FORM.search( s )
    if not m:
        return None
    kw = m.group( 1 ).upper()
    return "UPDATE" if kw in _UPDATE_KEYWORDS else kw

# --------------------------------------------------------------------------- #
# grlc parameter defaults substitution
# --------------------------------------------------------------------------- #

_PARAM = re.compile(
    r"\?(?P<req>_{1,2})(?P<name>[A-Za-z0-9]+)"
    r"(?:_(?P<type>iri|number|integer|literal))?"
    r"(?:_(?P<pfx>[A-Za-z0-9]+)_(?P<dt>[A-Za-z0-9]+))?"
    r"(?:_(?P<lang>[A-Za-z]+))?"
)

def _render_value( m, value ):
    t, lang, pfx, dt = m.group( "type" ), m.group( "lang" ), m.group( "pfx" ), m.group( "dt" )
    s = str( value )
    if t == "iri":
        return "<" + s + ">"
    if t in ( "number", "integer" ):
        return s
    if lang:
        return '"' + s + '"@' + lang
    if pfx and dt:
        return '"' + s + '"^^' + pfx + ":" + dt
    return '"' + s + '"'

def apply_defaults( text, decorators ):
    """Substitute grlc parameter `defaults` into *text*. Parameters without a
    default are left as valid SPARQL variables."""
    if decorators is None or not decorators.defaults:
        return text
    defaults = {}
    for entry in decorators.defaults:
        if isinstance( entry, dict ):
            defaults.update( entry )
    if not defaults:
        return text
    def repl( m ):
        name = m.group( "name" )
        return _render_value( m, defaults[ name ] ) if name in defaults else m.group( 0 )
    return _PARAM.sub( repl, text )

# --------------------------------------------------------------------------- #
# RDF documentation
# --------------------------------------------------------------------------- #

SH   = Namespace( "http://www.w3.org/ns/shacl#" )
SCH  = Namespace( "https://schema.org/" )
SPEX = Namespace( "https://purl.expasy.org/sparql-examples/ontology#" )
KG   = Namespace( "https://purl.expasy.org/kgsteward/" )
DCT  = Namespace( "http://purl.org/dc/terms/" )

_FALLBACK_BASE = str( KG ) + "query/"

_FORM_TO_SH = {
    "SELECT"    : ( SH.SPARQLSelectExecutable,    SH.select    ),
    "ASK"       : ( SH.SPARQLAskExecutable,       SH.ask       ),
    "CONSTRUCT" : ( SH.SPARQLConstructExecutable, SH.construct ),
    "DESCRIBE"  : ( SH.SPARQLDescribeExecutable,  SH.describe  ),
    "UPDATE"    : ( SH.SPARQLUpdateExecutable,    SH.update    ),
}

_WIDGET_CLASS = {
    "select"       : KG.SelectParam,
    "checkbox"     : KG.CheckboxParam,
    "autocomplete" : KG.AutocompleteParam,
    "text"         : KG.TextParam,
    "slider"       : KG.SliderParam,
}
_QUERY_BACKED = { "select", "checkbox", "autocomplete" }

def _bind( g ):
    g.bind( "sh", SH ); g.bind( "schema", SCH ); g.bind( "spex", SPEX )
    g.bind( "rdfs", RDFS ); g.bind( "kgsteward", KG ); g.bind( "dct", DCT )

def subject_iri( name, endpoint = None ):
    base = ( endpoint.rstrip( "/" ) + "/.well-known/sparql-examples/"
             if endpoint else _FALLBACK_BASE )
    return URIRef( base + name )

def _add_index( g, subj, idx_pred, var_pred, val ):
    if isinstance( val, bool ):                    # guard: bool is an int subclass
        val = int( val )
    if isinstance( val, int ):
        g.add(( subj, idx_pred, RdfLiteral( val, datatype = XSD.integer )))
    else:
        g.add(( subj, var_pred, RdfLiteral( str( val ))))

def _add_widget( g, w, default_options ):
    subj = KG[ w.id ]
    g.add(( subj, RDF.type, _WIDGET_CLASS[ w.type ] ))
    g.add(( subj, KG.prompt, RdfLiteral( w.prompt )))
    if w.type in _QUERY_BACKED:
        g.add(( subj, KG.selectQuery, KG[ w.options or default_options ] ))
        _add_index( g, subj, KG.valueIndex, KG.valueVar, w.valueIndex )
        _add_index( g, subj, KG.nameIndex,  KG.nameVar,  w.nameIndex )
    elif w.type == "text":
        if w.pattern:
            g.add(( subj, KG.pattern, RdfLiteral( w.pattern )))
    elif w.type == "slider":
        g.add(( subj, KG.min,  RdfLiteral( w.min )))
        g.add(( subj, KG.max,  RdfLiteral( w.max )))
        g.add(( subj, KG.step, RdfLiteral( w.step )))

def _add_form( g, name, fields ):
    form = KG[ "form_" + name ]
    g.add(( form, RDF.type, KG.InputForm ))
    g.add(( form, KG.selectQuery, KG[ name ] ))
    nodes = []
    for f in fields:
        b = BNode()
        g.add(( b, KG.targetStr,  RdfLiteral( f.target )))
        g.add(( b, KG.replaceWith, KG[ f.widget ] ))
        if f.default is not None:
            g.add(( b, KG.default, RdfLiteral( f.default )))
        nodes.append( b )
    lst = BNode()
    Collection( g, lst, nodes )
    g.add(( form, KG.inputField, lst ))

def build_graph( text, name, decorators, endpoint = None, form = None, graph = None ):
    """Add RDF documenting the query (sparql-examples + query-form extension)
    into *graph* (created if None) and return it. Query text is stored as
    authored."""
    g = graph
    if g is None:
        g = Graph(); _bind( g )
    subj = subject_iri( name, endpoint )

    g.add(( subj, RDF.type, SH.SPARQLExecutable ))
    if form in _FORM_TO_SH:
        cls, pred = _FORM_TO_SH[ form ]
        g.add(( subj, RDF.type, cls ))
        # Prepend a '#+ endpoint:' grlc directive so the published query is
        # self-describing, unless it already declares its own endpoint.
        own_endpoint = decorators.endpoint if decorators else None
        query_text = text
        if endpoint and not own_endpoint:
            query_text = "#+ endpoint: " + endpoint + "\n" + text
        g.add(( subj, pred, RdfLiteral( query_text )))

    if decorators:
        if decorators.summary:
            g.add(( subj, RDFS.label, RdfLiteral( decorators.summary )))
        comment = decorators.description or decorators.summary
        if comment:
            g.add(( subj, RDFS.comment, RdfLiteral( comment )))
        target = decorators.endpoint or endpoint
        if target:
            g.add(( subj, SCH.target, URIRef( target )))
        for tag in ( decorators.tags or [] ):
            g.add(( subj, SCH.keywords, RdfLiteral( tag )))
        if decorators.source:
            g.add(( subj, DCT.source, RdfLiteral( decorators.source )))
        if decorators.citation:
            g.add(( subj, SCH.citation, RdfLiteral( decorators.citation )))
        for w in ( decorators.selector or [] ):
            _add_widget( g, w, default_options = name )   # options default to this query
        if decorators.form:
            _add_form( g, name, decorators.form )

    return g

# --------------------------------------------------------------------------- #
# Per-query record & accumulating catalogue
# --------------------------------------------------------------------------- #

class GrlcQuery:
    """One parsed query: executable text + metadata + its IRI in the graph."""
    def __init__( self, name, text, query, decorators, form, subject ):
        self.name       = name
        self.text       = text        # as authored
        self.query      = query       # executable (defaults applied)
        self.decorators = decorators  # GrlcDecorators | None
        self.form       = form        # SELECT/ASK/... | None
        self.subject    = subject     # URIRef

class GrlcCatalog:
    """Accumulates parsed queries and their documentation into one graph.

    The graph is the single backing store consumed both by the sparql-editor
    (:meth:`serialize`) and by an MCP server (:meth:`list` / :meth:`get` /
    :meth:`search`, or SPARQL over ``self.graph``)."""

    def __init__( self ):
        self.graph = Graph(); _bind( self.graph )
        self.queries = []
        self._by_name = {}

    def parse( self, text, name, endpoint = None ):
        """Parse one query file, fold its documentation into the graph, and
        return the :class:`GrlcQuery`."""
        decorators = parse_decorators( text )
        form       = detect_form( text )
        query      = apply_defaults( text, decorators )
        subject    = subject_iri( name, endpoint )
        build_graph( text, name, decorators, endpoint = endpoint, form = form, graph = self.graph )
        q = GrlcQuery( name, text, query, decorators, form, subject )
        self.queries.append( q )
        self._by_name[ name ] = q
        return q

    def get( self, name ):
        return self._by_name.get( name )

    def list( self ):
        """Lightweight catalogue entries (name, form, summary, tags)."""
        out = []
        for q in self.queries:
            d = q.decorators
            out.append({
                "name"    : q.name,
                "form"    : q.form,
                "summary" : d.summary if d else None,
                "tags"    : d.tags if d else None,
            })
        return out

    def search( self, text = None, tags = None ):
        """Return GrlcQuery objects matching a substring (name/summary/
        description) and/or any of *tags*."""
        res = []
        for q in self.queries:
            d = q.decorators
            hay = " ".join( filter( None, [
                q.name,
                d.summary if d else None,
                d.description if d else None,
            ])).lower()
            if text and text.lower() not in hay:
                continue
            if tags:
                qtags = set( d.tags or [] ) if d else set()
                if not ( set( tags ) & qtags ):
                    continue
            res.append( q )
        return res

    def check( self ):
        """Cross-query validation, run after all files are parsed. Returns a
        list of human-readable problems (empty when consistent)."""
        problems  = []
        widget_ct = {}                                   # widget id -> definition count
        names     = { q.name for q in self.queries }
        for q in self.queries:
            d = q.decorators
            if not d:
                continue
            for w in ( d.selector or [] ):
                widget_ct[ w.id ] = widget_ct.get( w.id, 0 ) + 1
                opt = getattr( w, "options", None )
                if opt and opt not in names:
                    problems.append( f"{q.name}: selector '{w.id}' options query '{opt}' not found" )
        for wid, c in widget_ct.items():
            if c > 1:
                problems.append( f"duplicate selector id '{wid}' ({c} definitions)" )
        for q in self.queries:
            d = q.decorators
            if not d:
                continue
            body = strip_comments( q.text )    # ignore the #+ block: target must be in the executable body
            for f in ( d.form or [] ):
                if f.widget not in widget_ct:
                    problems.append( f"{q.name}: form references undefined widget '{f.widget}'" )
                if f.target not in body:
                    problems.append( f"{q.name}: form targetStr {f.target!r} not found in query body" )
        return problems

    def serialize( self, format = "turtle" ):
        return self.graph.serialize( format = format )

# --------------------------------------------------------------------------- #
# Single-query convenience (thin wrapper over GrlcCatalog)
# --------------------------------------------------------------------------- #

def parse_query( text, name, endpoint = None ):
    """Parse one query, returning ``(executable_query, rdflib.Graph)``."""
    cat = GrlcCatalog()
    q = cat.parse( text, name, endpoint )
    return q.query, cat.graph
